url: "https://thewillmoss.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
stylesheet: "/assets/css/main.css"
title: "Will Moss" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--more-->
header_pages:
  - /index.md
  - /blog.md
  - /resume.md
  - /portfolio.md
sass:
  sass_dir: assets/css
  style: :compressed
